import React from "react";
import { useNavigate } from "react-router-dom";

function About() {
    const navigate = useNavigate();
    const handleOnClick = () => {
        navigate("/");
    };
    return (
        <div>
            <div>About</div>
            <div>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec purus id elit cursus maximus nec vel orci. Sed mi odio, dapibus sed nibh a, volutpat accumsan nulla. Morbi eleifend, odio nec cursus porta, dui tellus elementum sapien, a auctor elit nisi sit amet leo. Aenean quis auctor elit. Quisque odio ex, congue ac erat et, efficitur vehicula mi. Donec quis nibh venenatis, bibendum enim eu, rutrum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget aliquet magna. In porttitor erat sed sem placerat consequat. Etiam convallis bibendum lorem, id tempor augue scelerisque ac. Fusce nunc tortor, iaculis ac urna id, pretium pretium neque. Sed mollis, sapien quis malesuada dictum, urna tortor euismod mauris, et dignissim lacus nisi id erat. Aenean sit amet sollicitudin dolor, at tempus risus. Nullam sit amet mollis ligula.

                Vivamus nec malesuada felis, at ullamcorper sem. Morbi convallis nibh at malesuada fringilla. Fusce quis tincidunt turpis. Nulla faucibus in sapien vel eleifend. Cras volutpat, dolor placerat feugiat elementum, mi nulla placerat lectus, nec commodo nibh velit a lectus. Proin at ex sed purus malesuada laoreet quis vitae mi. Aliquam vehicula lacus non sem ullamcorper, vitae laoreet mauris rhoncus. Sed et libero risus. Phasellus interdum risus eget consectetur placerat. Integer laoreet, sapien eget accumsan dapibus, orci velit imperdiet metus, quis dapibus quam urna in ligula. Quisque sed enim nec dui facilisis suscipit ultricies et mauris. Vestibulum malesuada sem in porta cursus. Quisque posuere scelerisque urna vitae auctor. Donec venenatis, sem in pellentesque mollis, eros turpis tempus tortor, vitae scelerisque quam est a urna.

                Integer elementum mauris ac hendrerit bibendum. Suspendisse vel pretium nunc, ac molestie magna. Phasellus imperdiet risus ultrices, tincidunt metus in, finibus justo. Sed ac nisl id eros cursus auctor. Donec vestibulum dictum mattis. Vivamus vestibulum eu orci eget vehicula. Aenean venenatis eros nisl, id tristique lectus finibus nec. Ut cursus imperdiet libero non laoreet. Donec mollis posuere purus sed fermentum. Curabitur aliquam, elit eu tincidunt posuere, nisl nibh aliquam enim, id placerat purus eros sed turpis. Sed dictum massa sit amet eros viverra, et hendrerit orci maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus condimentum ac metus luctus porta. Quisque tincidunt arcu gravida metus venenatis, quis sodales justo pretium. Fusce neque tortor, venenatis sed fermentum ac, sollicitudin a sapien. Cras id elit purus.

                Nulla facilisi. Quisque venenatis pulvinar euismod. Proin vitae fermentum lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas bibendum imperdiet odio, eu mattis arcu tempus ut. Nullam consequat vestibulum sem, non elementum mi consequat vel. Phasellus sed ultrices leo, ut euismod neque. Phasellus porta ullamcorper neque in ultrices. Fusce aliquet tincidunt augue, id feugiat dui feugiat sed.

                Cras dictum luctus blandit. Vestibulum blandit nibh id purus ultrices, a aliquam velit tristique. Vestibulum laoreet ligula vitae tristique ullamcorper. Aliquam suscipit mi et ipsum tempus aliquam. Suspendisse condimentum sed erat tristique bibendum. Etiam ex odio, efficitur ac varius vitae, aliquet accumsan nulla. Aliquam eget mattis nibh. Nulla facilisi. Nulla scelerisque fringilla quam sed aliquam. Vivamus rhoncus mauris ac dolor rhoncus sodales. Suspendisse vulputate dignissim odio sed eleifend. Nullam eget nunc consequat, fringilla elit sed, dignissim est. Proin vitae dictum nulla.

                Generated 5 paragraphs, 528 words, 3595 bytes of Lorem Ipsum
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec purus id elit cursus maximus nec vel orci. Sed mi odio, dapibus sed nibh a, volutpat accumsan nulla. Morbi eleifend, odio nec cursus porta, dui tellus elementum sapien, a auctor elit nisi sit amet leo. Aenean quis auctor elit. Quisque odio ex, congue ac erat et, efficitur vehicula mi. Donec quis nibh venenatis, bibendum enim eu, rutrum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget aliquet magna. In porttitor erat sed sem placerat consequat. Etiam convallis bibendum lorem, id tempor augue scelerisque ac. Fusce nunc tortor, iaculis ac urna id, pretium pretium neque. Sed mollis, sapien quis malesuada dictum, urna tortor euismod mauris, et dignissim lacus nisi id erat. Aenean sit amet sollicitudin dolor, at tempus risus. Nullam sit amet mollis ligula.

                Vivamus nec malesuada felis, at ullamcorper sem. Morbi convallis nibh at malesuada fringilla. Fusce quis tincidunt turpis. Nulla faucibus in sapien vel eleifend. Cras volutpat, dolor placerat feugiat elementum, mi nulla placerat lectus, nec commodo nibh velit a lectus. Proin at ex sed purus malesuada laoreet quis vitae mi. Aliquam vehicula lacus non sem ullamcorper, vitae laoreet mauris rhoncus. Sed et libero risus. Phasellus interdum risus eget consectetur placerat. Integer laoreet, sapien eget accumsan dapibus, orci velit imperdiet metus, quis dapibus quam urna in ligula. Quisque sed enim nec dui facilisis suscipit ultricies et mauris. Vestibulum malesuada sem in porta cursus. Quisque posuere scelerisque urna vitae auctor. Donec venenatis, sem in pellentesque mollis, eros turpis tempus tortor, vitae scelerisque quam est a urna.

                Integer elementum mauris ac hendrerit bibendum. Suspendisse vel pretium nunc, ac molestie magna. Phasellus imperdiet risus ultrices, tincidunt metus in, finibus justo. Sed ac nisl id eros cursus auctor. Donec vestibulum dictum mattis. Vivamus vestibulum eu orci eget vehicula. Aenean venenatis eros nisl, id tristique lectus finibus nec. Ut cursus imperdiet libero non laoreet. Donec mollis posuere purus sed fermentum. Curabitur aliquam, elit eu tincidunt posuere, nisl nibh aliquam enim, id placerat purus eros sed turpis. Sed dictum massa sit amet eros viverra, et hendrerit orci maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus condimentum ac metus luctus porta. Quisque tincidunt arcu gravida metus venenatis, quis sodales justo pretium. Fusce neque tortor, venenatis sed fermentum ac, sollicitudin a sapien. Cras id elit purus.

                Nulla facilisi. Quisque venenatis pulvinar euismod. Proin vitae fermentum lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas bibendum imperdiet odio, eu mattis arcu tempus ut. Nullam consequat vestibulum sem, non elementum mi consequat vel. Phasellus sed ultrices leo, ut euismod neque. Phasellus porta ullamcorper neque in ultrices. Fusce aliquet tincidunt augue, id feugiat dui feugiat sed.

                Cras dictum luctus blandit. Vestibulum blandit nibh id purus ultrices, a aliquam velit tristique. Vestibulum laoreet ligula vitae tristique ullamcorper. Aliquam suscipit mi et ipsum tempus aliquam. Suspendisse condimentum sed erat tristique bibendum. Etiam ex odio, efficitur ac varius vitae, aliquet accumsan nulla. Aliquam eget mattis nibh. Nulla facilisi. Nulla scelerisque fringilla quam sed aliquam. Vivamus rhoncus mauris ac dolor rhoncus sodales. Suspendisse vulputate dignissim odio sed eleifend. Nullam eget nunc consequat, fringilla elit sed, dignissim est. Proin vitae dictum nulla.

                Generated 5 paragraphs, 528 words, 3595 bytes of Lorem Ipsum
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec purus id elit cursus maximus nec vel orci. Sed mi odio, dapibus sed nibh a, volutpat accumsan nulla. Morbi eleifend, odio nec cursus porta, dui tellus elementum sapien, a auctor elit nisi sit amet leo. Aenean quis auctor elit. Quisque odio ex, congue ac erat et, efficitur vehicula mi. Donec quis nibh venenatis, bibendum enim eu, rutrum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget aliquet magna. In porttitor erat sed sem placerat consequat. Etiam convallis bibendum lorem, id tempor augue scelerisque ac. Fusce nunc tortor, iaculis ac urna id, pretium pretium neque. Sed mollis, sapien quis malesuada dictum, urna tortor euismod mauris, et dignissim lacus nisi id erat. Aenean sit amet sollicitudin dolor, at tempus risus. Nullam sit amet mollis ligula.

                Vivamus nec malesuada felis, at ullamcorper sem. Morbi convallis nibh at malesuada fringilla. Fusce quis tincidunt turpis. Nulla faucibus in sapien vel eleifend. Cras volutpat, dolor placerat feugiat elementum, mi nulla placerat lectus, nec commodo nibh velit a lectus. Proin at ex sed purus malesuada laoreet quis vitae mi. Aliquam vehicula lacus non sem ullamcorper, vitae laoreet mauris rhoncus. Sed et libero risus. Phasellus interdum risus eget consectetur placerat. Integer laoreet, sapien eget accumsan dapibus, orci velit imperdiet metus, quis dapibus quam urna in ligula. Quisque sed enim nec dui facilisis suscipit ultricies et mauris. Vestibulum malesuada sem in porta cursus. Quisque posuere scelerisque urna vitae auctor. Donec venenatis, sem in pellentesque mollis, eros turpis tempus tortor, vitae scelerisque quam est a urna.

                Integer elementum mauris ac hendrerit bibendum. Suspendisse vel pretium nunc, ac molestie magna. Phasellus imperdiet risus ultrices, tincidunt metus in, finibus justo. Sed ac nisl id eros cursus auctor. Donec vestibulum dictum mattis. Vivamus vestibulum eu orci eget vehicula. Aenean venenatis eros nisl, id tristique lectus finibus nec. Ut cursus imperdiet libero non laoreet. Donec mollis posuere purus sed fermentum. Curabitur aliquam, elit eu tincidunt posuere, nisl nibh aliquam enim, id placerat purus eros sed turpis. Sed dictum massa sit amet eros viverra, et hendrerit orci maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus condimentum ac metus luctus porta. Quisque tincidunt arcu gravida metus venenatis, quis sodales justo pretium. Fusce neque tortor, venenatis sed fermentum ac, sollicitudin a sapien. Cras id elit purus.

                Nulla facilisi. Quisque venenatis pulvinar euismod. Proin vitae fermentum lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas bibendum imperdiet odio, eu mattis arcu tempus ut. Nullam consequat vestibulum sem, non elementum mi consequat vel. Phasellus sed ultrices leo, ut euismod neque. Phasellus porta ullamcorper neque in ultrices. Fusce aliquet tincidunt augue, id feugiat dui feugiat sed.

                Cras dictum luctus blandit. Vestibulum blandit nibh id purus ultrices, a aliquam velit tristique. Vestibulum laoreet ligula vitae tristique ullamcorper. Aliquam suscipit mi et ipsum tempus aliquam. Suspendisse condimentum sed erat tristique bibendum. Etiam ex odio, efficitur ac varius vitae, aliquet accumsan nulla. Aliquam eget mattis nibh. Nulla facilisi. Nulla scelerisque fringilla quam sed aliquam. Vivamus rhoncus mauris ac dolor rhoncus sodales. Suspendisse vulputate dignissim odio sed eleifend. Nullam eget nunc consequat, fringilla elit sed, dignissim est. Proin vitae dictum nulla.

                Generated 5 paragraphs, 528 words, 3595 bytes of Lorem Ipsum
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec purus id elit cursus maximus nec vel orci. Sed mi odio, dapibus sed nibh a, volutpat accumsan nulla. Morbi eleifend, odio nec cursus porta, dui tellus elementum sapien, a auctor elit nisi sit amet leo. Aenean quis auctor elit. Quisque odio ex, congue ac erat et, efficitur vehicula mi. Donec quis nibh venenatis, bibendum enim eu, rutrum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget aliquet magna. In porttitor erat sed sem placerat consequat. Etiam convallis bibendum lorem, id tempor augue scelerisque ac. Fusce nunc tortor, iaculis ac urna id, pretium pretium neque. Sed mollis, sapien quis malesuada dictum, urna tortor euismod mauris, et dignissim lacus nisi id erat. Aenean sit amet sollicitudin dolor, at tempus risus. Nullam sit amet mollis ligula.

                Vivamus nec malesuada felis, at ullamcorper sem. Morbi convallis nibh at malesuada fringilla. Fusce quis tincidunt turpis. Nulla faucibus in sapien vel eleifend. Cras volutpat, dolor placerat feugiat elementum, mi nulla placerat lectus, nec commodo nibh velit a lectus. Proin at ex sed purus malesuada laoreet quis vitae mi. Aliquam vehicula lacus non sem ullamcorper, vitae laoreet mauris rhoncus. Sed et libero risus. Phasellus interdum risus eget consectetur placerat. Integer laoreet, sapien eget accumsan dapibus, orci velit imperdiet metus, quis dapibus quam urna in ligula. Quisque sed enim nec dui facilisis suscipit ultricies et mauris. Vestibulum malesuada sem in porta cursus. Quisque posuere scelerisque urna vitae auctor. Donec venenatis, sem in pellentesque mollis, eros turpis tempus tortor, vitae scelerisque quam est a urna.

                Integer elementum mauris ac hendrerit bibendum. Suspendisse vel pretium nunc, ac molestie magna. Phasellus imperdiet risus ultrices, tincidunt metus in, finibus justo. Sed ac nisl id eros cursus auctor. Donec vestibulum dictum mattis. Vivamus vestibulum eu orci eget vehicula. Aenean venenatis eros nisl, id tristique lectus finibus nec. Ut cursus imperdiet libero non laoreet. Donec mollis posuere purus sed fermentum. Curabitur aliquam, elit eu tincidunt posuere, nisl nibh aliquam enim, id placerat purus eros sed turpis. Sed dictum massa sit amet eros viverra, et hendrerit orci maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus condimentum ac metus luctus porta. Quisque tincidunt arcu gravida metus venenatis, quis sodales justo pretium. Fusce neque tortor, venenatis sed fermentum ac, sollicitudin a sapien. Cras id elit purus.

                Nulla facilisi. Quisque venenatis pulvinar euismod. Proin vitae fermentum lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas bibendum imperdiet odio, eu mattis arcu tempus ut. Nullam consequat vestibulum sem, non elementum mi consequat vel. Phasellus sed ultrices leo, ut euismod neque. Phasellus porta ullamcorper neque in ultrices. Fusce aliquet tincidunt augue, id feugiat dui feugiat sed.

                Cras dictum luctus blandit. Vestibulum blandit nibh id purus ultrices, a aliquam velit tristique. Vestibulum laoreet ligula vitae tristique ullamcorper. Aliquam suscipit mi et ipsum tempus aliquam. Suspendisse condimentum sed erat tristique bibendum. Etiam ex odio, efficitur ac varius vitae, aliquet accumsan nulla. Aliquam eget mattis nibh. Nulla facilisi. Nulla scelerisque fringilla quam sed aliquam. Vivamus rhoncus mauris ac dolor rhoncus sodales. Suspendisse vulputate dignissim odio sed eleifend. Nullam eget nunc consequat, fringilla elit sed, dignissim est. Proin vitae dictum nulla.

                Generated 5 paragraphs, 528 words, 3595 bytes of Lorem Ipsum
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec purus id elit cursus maximus nec vel orci. Sed mi odio, dapibus sed nibh a, volutpat accumsan nulla. Morbi eleifend, odio nec cursus porta, dui tellus elementum sapien, a auctor elit nisi sit amet leo. Aenean quis auctor elit. Quisque odio ex, congue ac erat et, efficitur vehicula mi. Donec quis nibh venenatis, bibendum enim eu, rutrum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget aliquet magna. In porttitor erat sed sem placerat consequat. Etiam convallis bibendum lorem, id tempor augue scelerisque ac. Fusce nunc tortor, iaculis ac urna id, pretium pretium neque. Sed mollis, sapien quis malesuada dictum, urna tortor euismod mauris, et dignissim lacus nisi id erat. Aenean sit amet sollicitudin dolor, at tempus risus. Nullam sit amet mollis ligula.

                Vivamus nec malesuada felis, at ullamcorper sem. Morbi convallis nibh at malesuada fringilla. Fusce quis tincidunt turpis. Nulla faucibus in sapien vel eleifend. Cras volutpat, dolor placerat feugiat elementum, mi nulla placerat lectus, nec commodo nibh velit a lectus. Proin at ex sed purus malesuada laoreet quis vitae mi. Aliquam vehicula lacus non sem ullamcorper, vitae laoreet mauris rhoncus. Sed et libero risus. Phasellus interdum risus eget consectetur placerat. Integer laoreet, sapien eget accumsan dapibus, orci velit imperdiet metus, quis dapibus quam urna in ligula. Quisque sed enim nec dui facilisis suscipit ultricies et mauris. Vestibulum malesuada sem in porta cursus. Quisque posuere scelerisque urna vitae auctor. Donec venenatis, sem in pellentesque mollis, eros turpis tempus tortor, vitae scelerisque quam est a urna.

                Integer elementum mauris ac hendrerit bibendum. Suspendisse vel pretium nunc, ac molestie magna. Phasellus imperdiet risus ultrices, tincidunt metus in, finibus justo. Sed ac nisl id eros cursus auctor. Donec vestibulum dictum mattis. Vivamus vestibulum eu orci eget vehicula. Aenean venenatis eros nisl, id tristique lectus finibus nec. Ut cursus imperdiet libero non laoreet. Donec mollis posuere purus sed fermentum. Curabitur aliquam, elit eu tincidunt posuere, nisl nibh aliquam enim, id placerat purus eros sed turpis. Sed dictum massa sit amet eros viverra, et hendrerit orci maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus condimentum ac metus luctus porta. Quisque tincidunt arcu gravida metus venenatis, quis sodales justo pretium. Fusce neque tortor, venenatis sed fermentum ac, sollicitudin a sapien. Cras id elit purus.

                Nulla facilisi. Quisque venenatis pulvinar euismod. Proin vitae fermentum lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas bibendum imperdiet odio, eu mattis arcu tempus ut. Nullam consequat vestibulum sem, non elementum mi consequat vel. Phasellus sed ultrices leo, ut euismod neque. Phasellus porta ullamcorper neque in ultrices. Fusce aliquet tincidunt augue, id feugiat dui feugiat sed.

                Cras dictum luctus blandit. Vestibulum blandit nibh id purus ultrices, a aliquam velit tristique. Vestibulum laoreet ligula vitae tristique ullamcorper. Aliquam suscipit mi et ipsum tempus aliquam. Suspendisse condimentum sed erat tristique bibendum. Etiam ex odio, efficitur ac varius vitae, aliquet accumsan nulla. Aliquam eget mattis nibh. Nulla facilisi. Nulla scelerisque fringilla quam sed aliquam. Vivamus rhoncus mauris ac dolor rhoncus sodales. Suspendisse vulputate dignissim odio sed eleifend. Nullam eget nunc consequat, fringilla elit sed, dignissim est. Proin vitae dictum nulla.

                Generated 5 paragraphs, 528 words, 3595 bytes of Lorem Ipsum
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec purus id elit cursus maximus nec vel orci. Sed mi odio, dapibus sed nibh a, volutpat accumsan nulla. Morbi eleifend, odio nec cursus porta, dui tellus elementum sapien, a auctor elit nisi sit amet leo. Aenean quis auctor elit. Quisque odio ex, congue ac erat et, efficitur vehicula mi. Donec quis nibh venenatis, bibendum enim eu, rutrum lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget aliquet magna. In porttitor erat sed sem placerat consequat. Etiam convallis bibendum lorem, id tempor augue scelerisque ac. Fusce nunc tortor, iaculis ac urna id, pretium pretium neque. Sed mollis, sapien quis malesuada dictum, urna tortor euismod mauris, et dignissim lacus nisi id erat. Aenean sit amet sollicitudin dolor, at tempus risus. Nullam sit amet mollis ligula.

                Vivamus nec malesuada felis, at ullamcorper sem. Morbi convallis nibh at malesuada fringilla. Fusce quis tincidunt turpis. Nulla faucibus in sapien vel eleifend. Cras volutpat, dolor placerat feugiat elementum, mi nulla placerat lectus, nec commodo nibh velit a lectus. Proin at ex sed purus malesuada laoreet quis vitae mi. Aliquam vehicula lacus non sem ullamcorper, vitae laoreet mauris rhoncus. Sed et libero risus. Phasellus interdum risus eget consectetur placerat. Integer laoreet, sapien eget accumsan dapibus, orci velit imperdiet metus, quis dapibus quam urna in ligula. Quisque sed enim nec dui facilisis suscipit ultricies et mauris. Vestibulum malesuada sem in porta cursus. Quisque posuere scelerisque urna vitae auctor. Donec venenatis, sem in pellentesque mollis, eros turpis tempus tortor, vitae scelerisque quam est a urna.

                Integer elementum mauris ac hendrerit bibendum. Suspendisse vel pretium nunc, ac molestie magna. Phasellus imperdiet risus ultrices, tincidunt metus in, finibus justo. Sed ac nisl id eros cursus auctor. Donec vestibulum dictum mattis. Vivamus vestibulum eu orci eget vehicula. Aenean venenatis eros nisl, id tristique lectus finibus nec. Ut cursus imperdiet libero non laoreet. Donec mollis posuere purus sed fermentum. Curabitur aliquam, elit eu tincidunt posuere, nisl nibh aliquam enim, id placerat purus eros sed turpis. Sed dictum massa sit amet eros viverra, et hendrerit orci maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus condimentum ac metus luctus porta. Quisque tincidunt arcu gravida metus venenatis, quis sodales justo pretium. Fusce neque tortor, venenatis sed fermentum ac, sollicitudin a sapien. Cras id elit purus.

                Nulla facilisi. Quisque venenatis pulvinar euismod. Proin vitae fermentum lacus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas bibendum imperdiet odio, eu mattis arcu tempus ut. Nullam consequat vestibulum sem, non elementum mi consequat vel. Phasellus sed ultrices leo, ut euismod neque. Phasellus porta ullamcorper neque in ultrices. Fusce aliquet tincidunt augue, id feugiat dui feugiat sed.

                Cras dictum luctus blandit. Vestibulum blandit nibh id purus ultrices, a aliquam velit tristique. Vestibulum laoreet ligula vitae tristique ullamcorper. Aliquam suscipit mi et ipsum tempus aliquam. Suspendisse condimentum sed erat tristique bibendum. Etiam ex odio, efficitur ac varius vitae, aliquet accumsan nulla. Aliquam eget mattis nibh. Nulla facilisi. Nulla scelerisque fringilla quam sed aliquam. Vivamus rhoncus mauris ac dolor rhoncus sodales. Suspendisse vulputate dignissim odio sed eleifend. Nullam eget nunc consequat, fringilla elit sed, dignissim est. Proin vitae dictum nulla.

                Generated 5 paragraphs, 528 words, 3595 bytes of Lorem Ipsum
            </div>
            <button onClick={() => handleOnClick()}>Go to Home</button>
        </div>
    );
}

export default About;
